# Generated by Django 4.1.7 on 2023-02-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nome',
        ),
    ]
