# Generated by Django 4.1.7 on 2023-02-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coca', models.IntegerField()),
                ('cerveja', models.IntegerField()),
                ('hamburguer', models.IntegerField()),
            ],
        ),
    ]
