# Generated by Django 4.1.7 on 2023-02-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estoque'),
            preserve_default=False,
        ),
    ]
