# Generated by Django 4.1.7 on 2023-02-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estoque',
        ),
    ]
